increment – rte-rrtmgp
increment Function
81 statements
Source File
public function increment(op_in, op_io) result(err_message)
Routines for array classes: incrementing a%increment(b) adds the values of a to b, changing b and leaving a untouched
Arguments
Type Intent Optional Attributes Name
class(ty_optical_props_arry), intent(in) :: op_in
class(ty_optical_props_arry), intent(inout) :: op_io
Return Value character(len=128)
Calls
Contents
None
Call graph
increment calls inc_nstream_by_1scalar_bybnd, increment_2stream_by_1scalar, inc_1scalar_by_nstream_bybnd, increment_2stream_by_nstream, inc_2stream_by_2stream_bybnd, increment_1scalar_by_2stream, inc_1scalar_by_2stream_bybnd, inc_1scalar_by_1scalar_bybnd, inc_nstream_by_nstream_bybnd, increment_nstream_by_nstream, increment_1scalar_by_nstream, inc_2stream_by_1scalar_bybnd, increment_1scalar_by_1scalar, inc_2stream_by_nstream_bybnd, increment_nstream_by_1scalar, increment_nstream_by_2stream, inc_nstream_by_2stream_bybnd, increment_2stream_by_2stream