rte_sw – rte-rrtmgp
rte_sw Function
124 statements
Source File
public function rte_sw(atmos, top_at_1, mu0, inc_flux, sfc_alb_dir, sfc_alb_dif, fluxes, inc_flux_dif) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_optical_props_arry), intent(in) :: atmos
logical, intent(in) :: top_at_1
real(kind=wp), intent(in), dimension(:) :: mu0
real(kind=wp), intent(in), dimension(:,:) :: inc_flux
real(kind=wp), intent(in), dimension(:,:) :: sfc_alb_dir
real(kind=wp), intent(in), dimension(:,:) :: sfc_alb_dif
class(ty_fluxes), intent(inout) :: fluxes
real(kind=wp), intent(in), optional dimension(:,:), target :: inc_flux_dif
Return Value character(len=128)
Calls
Called by
Contents
Source Code
rte_sw
Source Code
  function rte_sw(atmos, top_at_1,                 &
                  mu0, inc_flux,                   &
                  sfc_alb_dir, sfc_alb_dif,        &
                  fluxes, inc_flux_dif) result(error_msg)
    class(ty_optical_props_arry), intent(in   ) :: atmos           ! Optical properties provided as arrays
    logical,                      intent(in   ) :: top_at_1        ! Is the top of the domain at index 1?
                                                                   ! (if not, ordering is bottom-to-top)
    real(wp), dimension(:),       intent(in   ) :: mu0             ! cosine of solar zenith angle (ncol)
    real(wp), dimension(:,:),     intent(in   ) :: inc_flux,    &  ! incident flux at top of domain [W/m2] (ncol, ngpt)
                                                   sfc_alb_dir, &  ! surface albedo for direct and
                                                   sfc_alb_dif     ! diffuse radiation (nband, ncol)
    class(ty_fluxes),             intent(inout) :: fluxes          ! Class describing output calculations
    real(wp), dimension(:,:), optional, target, &
                                  intent(in   ) :: inc_flux_dif    ! incident diffuse flux at top of domain [W/m2] (ncol, ngpt)
    character(len=128)                          :: error_msg       ! If empty, calculation was successful
    ! --------------------------------
    !
    ! Local variables
    !
    integer     :: ncol, nlay, ngpt, nband
    integer     :: icol, ilev
    logical(wl) :: has_dif_bc, do_broadband
    real(wp), dimension(:,:,:), pointer             :: gpt_flux_up, gpt_flux_dn, gpt_flux_dir
    real(wp), dimension(:,:),   allocatable         :: sfc_alb_dir_gpt, sfc_alb_dif_gpt
    real(wp), dimension(:,:),   pointer             :: flux_dn_loc, flux_up_loc, flux_dir_loc
    real(wp), dimension(:,:),   pointer             :: inc_flux_diffuse
    real(wp), dimension(:,:,:), allocatable, target :: decoy3D
    real(wp), dimension(:,:),   allocatable, target :: decoy2D
    ! ------------------------------------------------------------------------------------
    ncol  = atmos%get_ncol()
    nlay  = atmos%get_nlay()
    ngpt  = atmos%get_ngpt()
    nband = atmos%get_nband()
    error_msg = ""
    ! ------------------------------------------------------------------------------------
    !
    ! Error checking -- consistency of sizes and validity of values
    !
    ! --------------------------------
    if(.not. fluxes%are_desired()) &
      error_msg = "rte_sw: no space allocated for fluxes"
    has_dif_bc = logical(present(inc_flux_dif), wl)
    !
    ! Sizes of input arrays
    !
    ! Copy variables whose sizes and values are checked to the GPU so the checks can happen there.
    !   No harm done if checks are not performed  (?)
    !$acc        data copyin(mu0, inc_flux, sfc_alb_dir, sfc_alb_dif)
    !$omp target data map(to:mu0, inc_flux, sfc_alb_dir, sfc_alb_dif)
    !$acc        data copyin(inc_flux_dif) if (has_dif_bc)
    !$omp target data map(to:inc_flux_dif) if (has_dif_bc)
    if(check_extents) then
      if(.not. extents_are(mu0, ncol)) &
        error_msg = "rte_sw: mu0 inconsistently sized"
      if(.not. extents_are(inc_flux, ncol, ngpt)) &
        error_msg = "rte_sw: inc_flux inconsistently sized"
      if(.not. extents_are(sfc_alb_dir, nband, ncol)) &
        error_msg = "rte_sw: sfc_alb_dir inconsistently sized"
      if(.not. extents_are(sfc_alb_dif, nband, ncol)) &
        error_msg = "rte_sw: sfc_alb_dif inconsistently sized"
      if(has_dif_bc) then
        if(.not. extents_are(inc_flux_dif, ncol, ngpt)) &
          error_msg = "rte_sw: inc_flux_dif inconsistently sized"
      end if
    end if
    !
    ! Values of input arrays
    !
    if(check_values) then
      if(any_vals_outside(mu0, 0._wp, 1._wp)) &
        error_msg = "rte_sw: one or more mu0 <= 0 or > 1"
      if(any_vals_less_than(inc_flux, 0._wp)) &
        error_msg = "rte_sw: one or more inc_flux < 0"
      if(any_vals_outside(sfc_alb_dir,  0._wp, 1._wp)) &
        error_msg = "rte_sw: sfc_alb_dir out of bounds [0,1]"
      if(any_vals_outside(sfc_alb_dif,  0._wp, 1._wp)) &
        error_msg = "rte_sw: sfc_alb_dif out of bounds [0,1]"
      if(has_dif_bc) then
        if(any_vals_less_than(inc_flux_dif, 0._wp)) &
          error_msg = "rte_sw: one or more inc_flux_dif < 0"
      end if
    end if
    ! ------------------------------------------------------------------------------------
    select type(fluxes)
      type is (ty_fluxes_broadband)
        do_broadband = .true._wl
        !
        ! Solvers will integrate in place (one g-point at a time on CPUs)
        !   so won't need big working arrays
        !
        allocate(decoy3D(ncol, nlay+1, ngpt))
        gpt_flux_up  => decoy3D
        gpt_flux_dn  => decoy3D
        gpt_flux_dir => decoy3D
        !
        ! Broadband fluxes class has three possible outputs; allocate memory for local use
        !   if one or more haven't been requested
        !
        if(associated(fluxes%flux_up)) then
          flux_up_loc => fluxes%flux_up
        else
          allocate(flux_up_loc(ncol, nlay+1))
        end if
        if(associated(fluxes%flux_dn)) then
          flux_dn_loc => fluxes%flux_dn
        else
          allocate(flux_dn_loc(ncol, nlay+1))
        end if
        if(associated(fluxes%flux_dn_dir)) then
          flux_dir_loc => fluxes%flux_dn_dir
        else
          allocate(flux_dir_loc(ncol, nlay+1))
        end if
        !$acc        enter data create(   flux_up_loc, flux_dn_loc, flux_dir_loc)
        !$omp target enter data map(alloc:flux_up_loc, flux_dn_loc, flux_dir_loc)
      class default
        !
        ! If broadband integrals aren't being computed, allocate working space
        !   and decoy addresses for spectrally-integrated fields
        !
        do_broadband = .false._wl
        allocate(decoy2D(ncol, nlay+1))
        flux_up_loc  => decoy2D
        flux_dn_loc  => decoy2D
        flux_dir_loc => decoy2D
        allocate(gpt_flux_up (ncol,nlay+1,ngpt), &
                 gpt_flux_dn (ncol,nlay+1,ngpt), &
                 gpt_flux_dir(ncol,nlay+1,ngpt))
    end select
    allocate(sfc_alb_dir_gpt(ncol, ngpt), sfc_alb_dif_gpt(ncol, ngpt))
    if(len_trim(error_msg) > 0) then
      if(len_trim(atmos%get_name()) > 0) &
        error_msg = trim(atmos%get_name()) // ': ' // trim(error_msg)
    end if
    ! Fluxes need to be copied out only if do_broadband is .true.
    !$acc        data copyin(   flux_up_loc,flux_dn_loc,flux_dir_loc) if (      do_broadband)
    !$omp target data map(to:   flux_up_loc,flux_dn_loc,flux_dir_loc) if (      do_broadband)
    !$acc        data create(   flux_up_loc,flux_dn_loc,flux_dir_loc) if (.not. do_broadband)
    !$omp target data map(alloc:flux_up_loc,flux_dn_loc,flux_dir_loc) if (.not. do_broadband)
    !$acc        data create(   gpt_flux_up,gpt_flux_dn,gpt_flux_dir) &
    !$acc             create(   sfc_alb_dir_gpt, sfc_alb_dif_gpt)
    !$omp target data map(alloc:gpt_flux_up,gpt_flux_dn,gpt_flux_dir) &
    !$omp             map(alloc:sfc_alb_dir_gpt, sfc_alb_dif_gpt)
    ! ------------------------------------------------------------------------------------
    ! Boundary conditions
    !   Lower boundary condition -- expand surface albedos by band to gpoints
    !     and switch dimension ordering
    call expand_and_transpose(atmos, sfc_alb_dir, sfc_alb_dir_gpt)
    call expand_and_transpose(atmos, sfc_alb_dif, sfc_alb_dif_gpt)
    !
    !   Diffuse flux boundary condition - will use values in optional arg or be set to 0
    !
    if (has_dif_bc) then
      inc_flux_diffuse => inc_flux_dif
      !$acc        enter data copyin(   inc_flux_diffuse)
      !$omp target enter data map(to:   inc_flux_diffuse)
    else
      allocate(inc_flux_diffuse(ncol, ngpt))
      !$acc        enter data create(   inc_flux_diffuse)
      !$omp target enter data map(alloc:inc_flux_diffuse)
      call zero_array(ncol, ngpt, inc_flux_diffuse)
    end if
    ! ------------------------------------------------------------------------------------
    if(check_values) error_msg =  atmos%validate()
    !
    ! Compute the radiative transfer...
    !
    if(len_trim(error_msg) == 0) then
      select type (atmos)
        class is (ty_optical_props_1scl)
          !
          ! Direct beam only - for completeness, unlikely to be used in practice
          !
          call sw_solver_noscat(ncol, nlay, ngpt, logical(top_at_1, wl), &
                                atmos%tau, mu0, inc_flux,                &
                                gpt_flux_dir)
          call zero_array(ncol, nlay+1, ngpt, gpt_flux_up)
          !
          !$acc kernels
          !$omp target
          gpt_flux_dn(:,:,:) = gpt_flux_dir(:,:,:)
          !$acc end kernels
          !$omp end target
        class is (ty_optical_props_2str)
          !
          ! two-stream calculation with scattering
          !
          call sw_solver_2stream(ncol, nlay, ngpt, logical(top_at_1, wl), &
                                 atmos%tau, atmos%ssa, atmos%g, mu0,      &
                                 sfc_alb_dir_gpt, sfc_alb_dif_gpt,        &
                                             inc_flux,                    &
                                 gpt_flux_up, gpt_flux_dn, gpt_flux_dir,  &
                                 has_dif_bc, inc_flux_diffuse,            &
                                 do_broadband, flux_up_loc, flux_dn_loc, flux_dir_loc)
        class is (ty_optical_props_nstr)
          !
          ! n-stream calculation
          !
          ! not yet implemented so fail
          !
          error_msg = 'sw_solver(...ty_optical_props_nstr...) not yet implemented'
      end select
      if(len_trim(error_msg) > 0) then
        if(len_trim(atmos%get_name()) > 0) &
          error_msg = trim(atmos%get_name()) // ': ' // trim(error_msg)
      end if
      !
      ! Flux reduction (summarizing for output)
      !
      select type(fluxes)
        !
        ! Tidy up memory for broadband fluxes
        !
        type is (ty_fluxes_broadband)
          if(associated(fluxes%flux_net)) then
            !$acc                         parallel loop    collapse(2) copyout(fluxes%flux_net)
            !$omp target teams distribute parallel do simd collapse(2)
            do ilev = 1, nlay+1
              do icol = 1, ncol
                fluxes%flux_net(icol,ilev) = flux_dn_loc(icol,ilev) - flux_up_loc(icol,ilev)
              end do
            end do
          end if
        class default
          !
          ! ...or reduce spectral fluxes to desired output quantities
          !
          error_msg = fluxes%reduce(gpt_flux_up, gpt_flux_dn, atmos, top_at_1, gpt_flux_dir)
      end select
    end if ! In case of an error we exit here
    !$acc        end data
    !$omp end target data
    !$acc        end data
    !$omp end target data
    !$acc        end data
    !$omp end target data
    !$acc        end data
    !$omp end target data
    !$acc        end data
    !$omp end target data
    !
    ! Deallocate any memory allocated locally to pointer variables
    !
    select type(fluxes)
      type is (ty_fluxes_broadband)
        !$acc        exit data copyout( flux_up_loc, flux_dn_loc, flux_dir_loc)
        !$omp target exit data map(from:flux_up_loc, flux_dn_loc, flux_dir_loc)
        if(.not. associated(fluxes%flux_up    )) deallocate(flux_up_loc)
        if(.not. associated(fluxes%flux_dn    )) deallocate(flux_dn_loc)
        if(.not. associated(fluxes%flux_dn_dir)) deallocate(flux_dir_loc)
      class default
        deallocate(gpt_flux_up, gpt_flux_dn, gpt_flux_dir)
    end select
    if(.not. has_dif_bc) then
      !$acc        exit data delete(     inc_flux_diffuse)
      !$omp target exit data map(release:inc_flux_diffuse)
      deallocate(inc_flux_diffuse)
    end if
  end function rte_sw
Call graph
rte_sw calls sw_solver_2stream, any_vals_less_than, zero_array, extents_are, sw_solver_noscat, any_vals_outside, rte_sw
compute_bc calls rte_sw