check_key_species_present – rte-rrtmgp
check_key_species_present Function
13 statements
Source File
private function check_key_species_present(this, gas_desc) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_optics_rrtmgp), intent(in) :: this
class(ty_gas_concs), intent(in) :: gas_desc
Return Value character(len=128)
Calls
Contents
None
Call graph
check_key_species_present calls string_in_array, lower_case
string_in_array calls lower_case