cloud_optics – rte-rrtmgp
cloud_optics Function
79 statements
Source File
private function cloud_optics(this, clwp, ciwp, reliq, reice, optical_props) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_cloud_optics), intent(in) :: this
real(kind=wp), intent(in) :: clwp(:,:)
real(kind=wp), intent(in) :: ciwp(:,:)
real(kind=wp), intent(in) :: reliq(:,:)
real(kind=wp), intent(in) :: reice(:,:)
class(ty_optical_props_arry), intent(inout) :: optical_props
Return Value character(len=128)
Calls
Contents
None
Call graph
cloud_optics calls compute_all_from_table, any_vals_less_than, any_vals_outside, compute_all_from_pade
any_vals_less_than calls any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_1d, any_vals_less_than_2d, any_vals_less_than_3d, any_vals_less_than_1d_masked
any_vals_outside calls any_vals_outside_2d, any_vals_outside_3d, any_vals_outside_1d, any_vals_outside_1d_masked, any_vals_outside_3d_masked, any_vals_outside_2d_masked
compute_all_from_pade calls pade_eval
pade_eval calls pade_eval_1, pade_eval_nbnd