combine_abs_and_rayleigh – rte-rrtmgp
combine_abs_and_rayleigh Subroutine
60 statements
Source File
private subroutine combine_abs_and_rayleigh(tau, tau_rayleigh, optical_props)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: tau
real(kind=wp), intent(in), dimension(:,:,:) :: tau_rayleigh
class(ty_optical_props_arry), intent(inout) :: optical_props
Calls
Called by
Contents
None
Call graph
combine_abs_and_rayleigh calls zero_array
zero_array calls zero_array_2d, zero_array_3d, zero_array_4d, zero_array_1d
compute_gas_taus calls combine_abs_and_rayleigh
gas_optics_ext calls compute_gas_taus
gas_optics_int calls compute_gas_taus