compute_heating_rate – rte-rrtmgp
compute_heating_rate Function
18 statements
Source File
public function compute_heating_rate(flux_up, flux_dn, plev, heating_rate) result(error_msg)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: flux_up
real(kind=wp), intent(in), dimension(:,:) :: flux_dn
real(kind=wp), intent(in), dimension(:,:) :: plev
real(kind=wp), intent(out), dimension(:,:) :: heating_rate
Return Value character(len=128)
Calls
Contents
None
Call graph
compute_heating_rate calls extents_are
extents_are calls extents_are_5d, extents_are_3d, extents_are_1d, extents_are_2d_int, extents_are_6d, extents_are_2d, extents_are_4d