compute_all_from_pade – rte-rrtmgp
compute_all_from_pade Subroutine
35 statements
Source File
private subroutine compute_all_from_pade(ncol, nlay, nbnd, nsizes, mask, lwp, re, m_ext, n_ext, re_bounds_ext, coeffs_ext, m_ssa, n_ssa, re_bounds_ssa, coeffs_ssa, m_asy, n_asy, re_bounds_asy, coeffs_asy, tau, taussa, taussag)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncol
integer, intent(in) :: nlay
integer, intent(in) :: nbnd
integer, intent(in) :: nsizes
logical(kind=wl), intent(in), dimension(ncol,nlay) :: mask
real(kind=wp), intent(in), dimension(ncol,nlay) :: lwp
real(kind=wp), intent(in), dimension(ncol,nlay) :: re
integer, intent(in) :: m_ext
integer, intent(in) :: n_ext
real(kind=wp), intent(in), dimension(nsizes+1) :: re_bounds_ext
real(kind=wp), intent(in), dimension(nbnd,nsizes,0:m_ext+n_ext) :: coeffs_ext
integer, intent(in) :: m_ssa
integer, intent(in) :: n_ssa
real(kind=wp), intent(in), dimension(nsizes+1) :: re_bounds_ssa
real(kind=wp), intent(in), dimension(nbnd,nsizes,0:m_ssa+n_ssa) :: coeffs_ssa
integer, intent(in) :: m_asy
integer, intent(in) :: n_asy
real(kind=wp), intent(in), dimension(nsizes+1) :: re_bounds_asy
real(kind=wp), intent(in), dimension(nbnd,nsizes,0:m_asy+n_asy) :: coeffs_asy
real(kind=wp), dimension(ncol,nlay,nbnd) :: tau
real(kind=wp), dimension(ncol,nlay,nbnd) :: taussa
real(kind=wp), dimension(ncol,nlay,nbnd) :: taussag
Calls
Called by
Contents
None
Call graph
compute_all_from_pade calls pade_eval
pade_eval calls pade_eval_1, pade_eval_nbnd
cloud_optics calls compute_all_from_pade