compute_gas_taus – rte-rrtmgp
compute_gas_taus Function
117 statements
Source File
private function compute_gas_taus(this, ncol, nlay, ngpt, nband, play, plev, tlay, gas_desc, optical_props, jtemp, jpress, jeta, tropo, fmajor, col_dry) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_optics_rrtmgp), intent(in) :: this
integer, intent(in) :: ncol
integer, intent(in) :: nlay
integer, intent(in) :: ngpt
integer, intent(in) :: nband
real(kind=wp), intent(in), dimension(:,:) :: play
real(kind=wp), intent(in), dimension(:,:) :: plev
real(kind=wp), intent(in), dimension(:,:) :: tlay
type(ty_gas_concs), intent(in) :: gas_desc
class(ty_optical_props_arry), intent(inout) :: optical_props
integer, intent(out), dimension(ncol, nlay) :: jtemp
integer, intent(out), dimension(ncol, nlay) :: jpress
integer, intent(out), dimension(2, ncol, nlay,get_nflav(this)) :: jeta
logical(kind=wl), intent(out), dimension(ncol, nlay) :: tropo
real(kind=wp), intent(out), dimension(2,2,2,ncol, nlay,get_nflav(this)) :: fmajor
real(kind=wp), intent(in), optional dimension(:,:), target :: col_dry
Return Value character(len=128)
Calls
Called by
Contents
None
Call graph
compute_gas_taus calls zero_array, lower_case, interpolation, any_vals_outside, string_loc_in_array, get_nflav, compute_tau_rayleigh, extents_are, compute_tau_absorption, get_col_dry, any_vals_less_than, combine_abs_and_rayleigh
zero_array calls zero_array_4d, zero_array_2d, zero_array_3d, zero_array_1d
interpolation calls float
any_vals_outside calls any_vals_outside_2d_masked, any_vals_outside_3d, any_vals_outside_2d, any_vals_outside_1d, any_vals_outside_3d_masked, any_vals_outside_1d_masked
string_loc_in_array calls lower_case
compute_tau_rayleigh calls interpolate2d_byflav
extents_are calls extents_are_2d_int, extents_are_1d, extents_are_5d, extents_are_6d, extents_are_2d, extents_are_3d, extents_are_4d
compute_tau_absorption calls gas_optical_depths_minor, gas_optical_depths_major
any_vals_less_than calls any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_2d, any_vals_less_than_1d, any_vals_less_than_3d, any_vals_less_than_1d_masked
combine_abs_and_rayleigh calls zero_array
gas_optical_depths_minor calls interpolate2d_byflav
gas_optical_depths_major calls interpolate3d_byflav
gas_optics_ext calls compute_gas_taus
gas_optics_int calls compute_gas_taus