compute_bc – rte-rrtmgp
compute_bc Function
81 statements
Source File
public function compute_bc(k_dist, play, plev, tlay, gas_concs, flux_bc, mu0) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_optics), intent(in) :: k_dist
real(kind=wp), intent(in), dimension(:,:) :: play
real(kind=wp), intent(in), dimension(:,:) :: plev
real(kind=wp), intent(in), dimension(:,:) :: tlay
type(ty_gas_concs), intent(in) :: gas_concs
real(kind=wp), intent(out), dimension(:,:), target :: flux_bc
real(kind=wp), intent(in), optional dimension(:) :: mu0
Return Value character(len=128)
Calls
Contents
None
Call graph
compute_bc calls rte_sw, extents_are, rte_lw
rte_sw calls extents_are, sw_solver_noscat, zero_array, any_vals_outside, expand_and_transpose, sw_solver_2stream, any_vals_less_than
extents_are calls extents_are_5d, extents_are_4d, extents_are_3d, extents_are_1d, extents_are_2d_int, extents_are_6d, extents_are_2d
rte_lw calls extents_are, zero_array, expand_and_transpose, any_vals_outside, lw_solver_2stream, lw_solver_noscat_gaussquad, any_vals_less_than
zero_array calls zero_array_4d, zero_array_2d, zero_array_3d, zero_array_1d
any_vals_outside calls any_vals_outside_2d_masked, any_vals_outside_3d, any_vals_outside_2d, any_vals_outside_1d, any_vals_outside_3d_masked, any_vals_outside_1d_masked
lw_solver_2stream calls lw_source_2str, lw_combine_sources, adding, lw_two_stream
sw_solver_2stream calls zero_array, sw_dif_and_source, adding
any_vals_less_than calls any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_2d, any_vals_less_than_1d, any_vals_less_than_3d, any_vals_less_than_1d_masked