create_gpoint_flavor – rte-rrtmgp
create_gpoint_flavor Subroutine
14 statements
Source File
private subroutine create_gpoint_flavor(key_species, gpt2band, flavor, gpoint_flavor)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:,:,:) :: key_species
integer, intent(in), dimension(:) :: gpt2band
integer, intent(in), dimension(:,:) :: flavor
integer, intent(out), dimension(:,:), allocatable :: gpoint_flavor
Calls
Called by
Contents
None
Call graph
create_gpoint_flavor calls key_species_pair2flavor, rewrite_key_species_pair
init_abs_coeffs calls create_gpoint_flavor
load_int calls init_abs_coeffs
load_ext calls init_abs_coeffs