delta_scale_2str – rte-rrtmgp
delta_scale_2str Function
27 statements
Source File
public function delta_scale_2str(this, for) result(err_message)
Arguments
Type Intent Optional Attributes Name
class(ty_optical_props_2str), intent(inout) :: this
real(kind=wp), intent(in), optional dimension(:,:,:) :: for
Return Value character(len=128)
Calls
Contents
None
Call graph
delta_scale_2str calls delta_scale_2str_kernel, extents_are, any_vals_outside
delta_scale_2str_kernel calls delta_scale_2str_f_k, delta_scale_2str_k
extents_are calls extents_are_5d, extents_are_2d, extents_are_3d, extents_are_1d, extents_are_2d_int, extents_are_6d, extents_are_4d
any_vals_outside calls any_vals_outside_2d, any_vals_outside_3d, any_vals_outside_1d, any_vals_outside_1d_masked, any_vals_outside_3d_masked, any_vals_outside_2d_masked