extract_subset_dim2_4d – rte-rrtmgp
extract_subset_dim2_4d Subroutine
16 statements
Source File
public subroutine extract_subset_dim2_4d(nmom, ncol, nlay, ngpt, array_in, colS, colE, array_out) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nmom
integer, intent(in) :: ncol
integer, intent(in) :: nlay
integer, intent(in) :: ngpt
real(kind=wp), intent(in), dimension(nmom,ncol,nlay,ngpt) :: array_in
integer, intent(in) :: colS
integer, intent(in) :: colE
real(kind=wp), intent(out), dimension(nmom,colE-colS+1, nlay,ngpt) :: array_out
Called by
Contents
None
Call graph
extract_subset calls extract_subset_dim2_4d
subset_1scl_range calls extract_subset
subset_nstr_range calls extract_subset
subset_2str_range calls extract_subset