gas_optics_int – rte-rrtmgp
gas_optics_int Function
41 statements
Source File
private function gas_optics_int(this, play, plev, tlay, tsfc, gas_desc, optical_props, sources, col_dry, tlev) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_optics_rrtmgp), intent(in) :: this
real(kind=wp), intent(in), dimension(:,:) :: play
real(kind=wp), intent(in), dimension(:,:) :: plev
real(kind=wp), intent(in), dimension(:,:) :: tlay
real(kind=wp), intent(in), dimension(:) :: tsfc
type(ty_gas_concs), intent(in) :: gas_desc
class(ty_optical_props_arry), intent(inout) :: optical_props
class(ty_source_func_lw), intent(inout) :: sources
real(kind=wp), intent(in), optional dimension(:,:), target :: col_dry
real(kind=wp), intent(in), optional dimension(:,:), target :: tlev
Return Value character(len=128)
Calls
Contents
None
Call graph
gas_optics_int calls any_vals_outside, extents_are, compute_gas_taus, source
any_vals_outside calls any_vals_outside_2d_masked, any_vals_outside_3d, any_vals_outside_2d, any_vals_outside_1d, any_vals_outside_3d_masked, any_vals_outside_1d_masked
extents_are calls extents_are_2d_int, extents_are_4d, extents_are_1d, extents_are_5d, extents_are_6d, extents_are_2d, extents_are_3d
compute_gas_taus calls any_vals_outside, extents_are, get_nflav, lower_case, interpolation, string_loc_in_array, compute_tau_rayleigh, get_col_dry, zero_array, combine_abs_and_rayleigh, compute_tau_absorption, any_vals_less_than
source calls get_nflav, compute_planck_source
interpolation calls float
string_loc_in_array calls lower_case
compute_tau_rayleigh calls interpolate2d_byflav
zero_array calls zero_array_4d, zero_array_2d, zero_array_3d, zero_array_1d
combine_abs_and_rayleigh calls zero_array
compute_tau_absorption calls gas_optical_depths_minor, gas_optical_depths_major
any_vals_less_than calls any_vals_less_than_1d_masked, any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_3d, any_vals_less_than_1d, any_vals_less_than_2d
gas_optical_depths_minor calls interpolate2d_byflav
gas_optical_depths_major calls interpolate3d_byflav