gas_optical_depths_minor – rte-rrtmgp
gas_optical_depths_minor Subroutine
54 statements
Source File
public subroutine gas_optical_depths_minor(ncol, nlay, ngpt, ngas, nflav, ntemp, neta, nminor, nminork, idx_h2o, gpt_flv, kminor, minor_limits_gpt, minor_scales_with_density, scale_by_complement, idx_minor, idx_minor_scaling, kminor_start, play, tlay, col_gas, fminor, jeta, layer_limits, jtemp, tau) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncol
integer, intent(in) :: nlay
integer, intent(in) :: ngpt
integer, intent(in) :: ngas
integer, intent(in) :: nflav
integer, intent(in) :: ntemp
integer, intent(in) :: neta
integer, intent(in) :: nminor
integer, intent(in) :: nminork
integer, intent(in) :: idx_h2o
integer, intent(in), dimension(ngpt) :: gpt_flv
real(kind=wp), intent(in), dimension(ntemp,neta,nminork) :: kminor
integer, intent(in), dimension(2,nminor) :: minor_limits_gpt
logical(kind=wl), intent(in), dimension(nminor) :: minor_scales_with_density
logical(kind=wl), intent(in), dimension(nminor) :: scale_by_complement
integer, intent(in), dimension(nminor) :: idx_minor
integer, intent(in), dimension(nminor) :: idx_minor_scaling
integer, intent(in), dimension(nminor) :: kminor_start
real(kind=wp), intent(in), dimension(ncol,nlay) :: play
real(kind=wp), intent(in), dimension(ncol,nlay) :: tlay
real(kind=wp), intent(in), dimension(ncol,nlay,0:ngas) :: col_gas
real(kind=wp), intent(in), dimension(2,2,ncol,nlay,nflav) :: fminor
integer, intent(in), dimension(2, ncol,nlay,nflav) :: jeta
integer, intent(in), dimension(ncol, 2) :: layer_limits
integer, intent(in), dimension(ncol,nlay) :: jtemp
real(kind=wp), intent(inout), dimension(ncol,nlay,ngpt) :: tau
Calls
Called by
Contents
None
Call graph
gas_optical_depths_minor calls interpolate2d_byflav
compute_tau_absorption calls gas_optical_depths_minor
compute_gas_taus calls compute_tau_absorption
gas_optics_ext calls compute_gas_taus
gas_optics_int calls compute_gas_taus