gas_optics_ext – rte-rrtmgp
gas_optics_ext Function
32 statements
Source File
private function gas_optics_ext(this, play, plev, tlay, gas_desc, optical_props, toa_src, col_dry) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_optics_rrtmgp), intent(in) :: this
real(kind=wp), intent(in), dimension(:,:) :: play
real(kind=wp), intent(in), dimension(:,:) :: plev
real(kind=wp), intent(in), dimension(:,:) :: tlay
type(ty_gas_concs), intent(in) :: gas_desc
class(ty_optical_props_arry), intent(inout) :: optical_props
real(kind=wp), intent(out), dimension(:,:) :: toa_src
real(kind=wp), intent(in), optional dimension(:,:), target :: col_dry
Return Value character(len=128)
Calls
Contents
None
Call graph
gas_optics_ext calls get_nflav, extents_are, compute_gas_taus
extents_are calls extents_are_5d, extents_are_3d, extents_are_1d, extents_are_2d_int, extents_are_6d, extents_are_2d, extents_are_4d
compute_gas_taus calls get_nflav, extents_are, zero_array, lower_case, interpolation, any_vals_outside, string_loc_in_array, any_vals_less_than, compute_tau_rayleigh, compute_tau_absorption, get_col_dry, combine_abs_and_rayleigh
zero_array calls zero_array_4d, zero_array_2d, zero_array_3d, zero_array_1d
interpolation calls float
any_vals_outside calls any_vals_outside_2d_masked, any_vals_outside_3d, any_vals_outside_2d, any_vals_outside_1d, any_vals_outside_3d_masked, any_vals_outside_1d_masked
string_loc_in_array calls lower_case
any_vals_less_than calls any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_2d, any_vals_less_than_1d, any_vals_less_than_3d, any_vals_less_than_1d_masked
compute_tau_rayleigh calls interpolate2d_byflav
compute_tau_absorption calls gas_optical_depths_minor, gas_optical_depths_major
combine_abs_and_rayleigh calls zero_array
gas_optical_depths_minor calls interpolate2d_byflav
gas_optical_depths_major calls interpolate3d_byflav