init_base – rte-rrtmgp
init_base Function
40 statements
Source File
public function init_base(this, band_lims_wvn, band_lims_gpt, name) result(err_message)
Arguments
Type Intent Optional Attributes Name
class(ty_optical_props), intent(inout) :: this
real(kind=wp), intent(in), dimension(:,:) :: band_lims_wvn
integer, intent(in), optional dimension(:,:) :: band_lims_gpt
character(len=*), intent(in), optional :: name
Return Value character(len=128)
Calls
Contents
None
Call graph
init_base calls extents_are, any_vals_less_than
extents_are calls extents_are_5d, extents_are_3d, extents_are_1d, extents_are_2d_int, extents_are_6d, extents_are_2d, extents_are_4d
any_vals_less_than calls any_vals_less_than_1d, any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_3d, any_vals_less_than_2d, any_vals_less_than_1d_masked