interpolate3D_byflav – rte-rrtmgp
interpolate3D_byflav Function
14 statements
Source File
public pure function interpolate3D_byflav(scaling, fmajor, k, gptS, gptE, jeta, jtemp, jpress) result(res)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(2) :: scaling
real(kind=wp), intent(in), dimension(2,2,2) :: fmajor
real(kind=wp), intent(in), dimension(:,:,:,:) :: k
integer, intent(in) :: gptS
integer, intent(in) :: gptE
integer, intent(in), dimension(2) :: jeta
integer, intent(in) :: jtemp
integer, intent(in) :: jpress
Return Value real(kind=wp), dimension(gptE-gptS+1)
Called by
Contents
None
Call graph
gas_optical_depths_major calls interpolate3d_byflav
compute_planck_source calls interpolate3d_byflav
compute_tau_absorption calls gas_optical_depths_major
compute_gas_taus calls compute_tau_absorption
gas_optics_ext calls compute_gas_taus
gas_optics_int calls compute_gas_taus