load_lut – rte-rrtmgp
load_lut Function
38 statements
Source File
private function load_lut(this, band_lims_wvn, radliq_lwr, radliq_upr, radliq_fac, radice_lwr, radice_upr, radice_fac, lut_extliq, lut_ssaliq, lut_asyliq, lut_extice, lut_ssaice, lut_asyice) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_cloud_optics), intent(inout) :: this
real(kind=wp), intent(in), dimension(:,:) :: band_lims_wvn
real(kind=wp), intent(in) :: radliq_lwr
real(kind=wp), intent(in) :: radliq_upr
real(kind=wp), intent(in) :: radliq_fac
real(kind=wp), intent(in) :: radice_lwr
real(kind=wp), intent(in) :: radice_upr
real(kind=wp), intent(in) :: radice_fac
real(kind=wp), intent(in), dimension(:,:) :: lut_extliq
real(kind=wp), intent(in), dimension(:,:) :: lut_ssaliq
real(kind=wp), intent(in), dimension(:,:) :: lut_asyliq
real(kind=wp), intent(in), dimension(:,:,:) :: lut_extice
real(kind=wp), intent(in), dimension(:,:,:) :: lut_ssaice
real(kind=wp), intent(in), dimension(:,:,:) :: lut_asyice
Return Value character(len=128)
Calls
Contents
None
Call graph
load_lut calls extents_are
extents_are calls extents_are_5d, extents_are_3d, extents_are_1d, extents_are_2d_int, extents_are_6d, extents_are_2d, extents_are_4d