load_ext – rte-rrtmgp
load_ext Function
33 statements
Source File
private function load_ext(this, available_gases, gas_names, key_species, band2gpt, band_lims_wavenum, press_ref, press_ref_trop, temp_ref, temp_ref_p, temp_ref_t, vmr_ref, kmajor, kminor_lower, kminor_upper, gas_minor, identifier_minor, minor_gases_lower, minor_gases_upper, minor_limits_gpt_lower, minor_limits_gpt_upper, minor_scales_with_density_lower, minor_scales_with_density_upper, scaling_gas_lower, scaling_gas_upper, scale_by_complement_lower, scale_by_complement_upper, kminor_start_lower, kminor_start_upper, solar_quiet, solar_facular, solar_sunspot, tsi_default, mg_default, sb_default, rayl_lower, rayl_upper) result(err_message)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_optics_rrtmgp), intent(inout) :: this
class(ty_gas_concs), intent(in) :: available_gases
character(len=*), intent(in), dimension(:) :: gas_names
integer, intent(in), dimension(:,:,:) :: key_species
integer, intent(in), dimension(:,:) :: band2gpt
real(kind=wp), intent(in), dimension(:,:) :: band_lims_wavenum
real(kind=wp), intent(in), dimension(:) :: press_ref
real(kind=wp), intent(in) :: press_ref_trop
real(kind=wp), intent(in), dimension(:) :: temp_ref
real(kind=wp), intent(in) :: temp_ref_p
real(kind=wp), intent(in) :: temp_ref_t
real(kind=wp), intent(in), dimension(:,:,:) :: vmr_ref
real(kind=wp), intent(in), dimension(:,:,:,:) :: kmajor
real(kind=wp), intent(in), dimension(:,:,:) :: kminor_lower
real(kind=wp), intent(in), dimension(:,:,:) :: kminor_upper
character(len=*), intent(in), dimension(:) :: gas_minor
character(len=*), intent(in), dimension(:) :: identifier_minor
character(len=*), intent(in), dimension(:) :: minor_gases_lower
character(len=*), intent(in), dimension(:) :: minor_gases_upper
integer, intent(in), dimension(:,:) :: minor_limits_gpt_lower
integer, intent(in), dimension(:,:) :: minor_limits_gpt_upper
logical(kind=wl), intent(in), dimension(:) :: minor_scales_with_density_lower
logical(kind=wl), intent(in), dimension(:) :: minor_scales_with_density_upper
character(len=*), intent(in), dimension(:) :: scaling_gas_lower
character(len=*), intent(in), dimension(:) :: scaling_gas_upper
logical(kind=wl), intent(in), dimension(:) :: scale_by_complement_lower
logical(kind=wl), intent(in), dimension(:) :: scale_by_complement_upper
integer, intent(in), dimension(:) :: kminor_start_lower
integer, intent(in), dimension(:) :: kminor_start_upper
real(kind=wp), intent(in), dimension(:) :: solar_quiet
real(kind=wp), intent(in), dimension(:) :: solar_facular
real(kind=wp), intent(in), dimension(:) :: solar_sunspot
real(kind=wp), intent(in) :: tsi_default
real(kind=wp), intent(in) :: mg_default
real(kind=wp), intent(in) :: sb_default
real(kind=wp), intent(in), dimension(:,:,:), allocatable :: rayl_lower
real(kind=wp), intent(in), dimension(:,:,:), allocatable :: rayl_upper
Return Value character(len=128)
Calls
Contents
None
Call graph
load_ext calls init_abs_coeffs
init_abs_coeffs calls check_key_species_present_init, create_idx_minor_scaling, reduce_minor_arrays, string_loc_in_array, string_in_array, create_idx_minor, create_key_species_reduce, create_gpoint_flavor, create_flavor
create_idx_minor_scaling calls string_loc_in_array
reduce_minor_arrays calls string_loc_in_array, string_in_array
string_loc_in_array calls lower_case
string_in_array calls lower_case
create_idx_minor calls string_loc_in_array
create_key_species_reduce calls string_loc_in_array
create_gpoint_flavor calls key_species_pair2flavor, rewrite_key_species_pair
create_flavor calls key_species_pair_exists, rewrite_key_species_pair