lower_case – rte-rrtmgp
lower_case Function
10 statements
Source File
public pure function lower_case(input_string) result(output_string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_string
Return Value character(len=len)
Called by
Contents
None
Call graph
find_gas calls lower_case
init calls lower_case
string_loc_in_array calls lower_case
string_in_array calls lower_case
compute_gas_taus calls lower_case, string_loc_in_array
check_key_species_present calls lower_case, string_in_array
create_idx_minor_scaling calls string_loc_in_array
reduce_minor_arrays calls string_loc_in_array, string_in_array
create_idx_minor calls string_loc_in_array
create_key_species_reduce calls string_loc_in_array
gas_optics_ext calls compute_gas_taus
init_abs_coeffs calls string_loc_in_array, string_in_array, create_idx_minor_scaling, reduce_minor_arrays, create_idx_minor, create_key_species_reduce
gas_optics_int calls compute_gas_taus
load_int calls init_abs_coeffs
load_ext calls init_abs_coeffs