lw_solver_noscat_GaussQuad – rte-rrtmgp
lw_solver_noscat_GaussQuad Subroutine
71 statements
Source File
public subroutine lw_solver_noscat_GaussQuad(ncol, nlay, ngpt, top_at_1, nmus, Ds, weights, tau, lay_source, lev_source_inc, lev_source_dec, sfc_emis, sfc_src, inc_flux, flux_up, flux_dn, do_broadband, broadband_up, broadband_dn, do_Jacobians, sfc_srcJac, flux_upJac, do_rescaling, ssa, g) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncol
integer, intent(in) :: nlay
integer, intent(in) :: ngpt
logical(kind=wl), intent(in) :: top_at_1
integer, intent(in) :: nmus
real(kind=wp), intent(in), dimension (ncol, ngpt, nmus) :: Ds
real(kind=wp), intent(in), dimension(nmus) :: weights
real(kind=wp), intent(in), dimension(ncol,nlay, ngpt) :: tau
real(kind=wp), intent(in), dimension(ncol,nlay, ngpt) :: lay_source
real(kind=wp), intent(in), dimension(ncol,nlay, ngpt) :: lev_source_inc
real(kind=wp), intent(in), dimension(ncol,nlay, ngpt) :: lev_source_dec
real(kind=wp), intent(in), dimension(ncol, ngpt) :: sfc_emis
real(kind=wp), intent(in), dimension(ncol, ngpt) :: sfc_src
real(kind=wp), intent(in), dimension(ncol, ngpt) :: inc_flux
real(kind=wp), intent(out), dimension(ncol,nlay+1,ngpt), target :: flux_up
real(kind=wp), intent(out), dimension(ncol,nlay+1,ngpt), target :: flux_dn
logical(kind=wl), intent(in) :: do_broadband
real(kind=wp), intent(inout), dimension(ncol,nlay+1), target :: broadband_up
real(kind=wp), intent(inout), dimension(ncol,nlay+1), target :: broadband_dn
logical(kind=wl), intent(in) :: do_Jacobians
real(kind=wp), intent(in), dimension(ncol ,ngpt) :: sfc_srcJac
real(kind=wp), intent(out), dimension(ncol,nlay+1), target :: flux_upJac
logical(kind=wl), intent(in) :: do_rescaling
real(kind=wp), intent(in), dimension(ncol,nlay ,ngpt) :: ssa
real(kind=wp), intent(in), dimension(ncol,nlay ,ngpt) :: g
Calls
Contents
None
Call graph
lw_solver_noscat_gaussquad calls lw_solver_noscat, add_arrays
lw_solver_noscat calls lw_transport_1rescl, apply_factor_3d, sum_broadband_factor, lw_source_noscat, lw_transport_noscat_dn, lw_transport_noscat_up
add_arrays calls add_arrays_3d, add_arrays_2d