lw_solver_2stream – rte-rrtmgp
lw_solver_2stream Subroutine
29 statements
Source File
public subroutine lw_solver_2stream(ncol, nlay, ngpt, top_at_1, tau, ssa, g, lay_source, lev_source_inc, lev_source_dec, sfc_emis, sfc_src, inc_flux, flux_up, flux_dn) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncol
integer, intent(in) :: nlay
integer, intent(in) :: ngpt
logical(kind=wl), intent(in) :: top_at_1
real(kind=wp), intent(in), dimension(ncol,nlay, ngpt) :: tau
real(kind=wp), intent(in), dimension(ncol,nlay, ngpt) :: ssa
real(kind=wp), intent(in), dimension(ncol,nlay, ngpt) :: g
real(kind=wp), intent(in), dimension(ncol,nlay,ngpt) :: lay_source
real(kind=wp), intent(in), dimension(ncol,nlay,ngpt), target :: lev_source_inc
real(kind=wp), intent(in), dimension(ncol,nlay,ngpt), target :: lev_source_dec
real(kind=wp), intent(in), dimension(ncol, ngpt) :: sfc_emis
real(kind=wp), intent(in), dimension(ncol, ngpt) :: sfc_src
real(kind=wp), intent(in), dimension(ncol, ngpt) :: inc_flux
real(kind=wp), intent(out), dimension(ncol,nlay+1,ngpt) :: flux_up
real(kind=wp), intent(out), dimension(ncol,nlay+1,ngpt) :: flux_dn
Calls
Contents
None
Call graph
lw_solver_2stream calls lw_two_stream, lw_source_2str, adding, lw_combine_sources