reduce_byband – rte-rrtmgp
reduce_byband Function
57 statements
Source File
public function reduce_byband(this, gpt_flux_up, gpt_flux_dn, spectral_disc, top_at_1, gpt_flux_dn_dir) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_fluxes_byband), intent(inout) :: this
real(kind=wp), intent(in), dimension(:,:,:) :: gpt_flux_up
real(kind=wp), intent(in), dimension(:,:,:) :: gpt_flux_dn
class(ty_optical_props), intent(in) :: spectral_disc
logical, intent(in) :: top_at_1
real(kind=wp), intent(in), optional dimension(:,:,:) :: gpt_flux_dn_dir
Return Value character(len=128)
Calls
Contents
None
Call graph
reduce_byband calls net_byband, extents_are, sum_byband
net_byband calls net_byband_precalc, net_byband_full
extents_are calls extents_are_5d, extents_are_3d, extents_are_1d, extents_are_2d_int, extents_are_6d, extents_are_2d, extents_are_4d