reduce_broadband – rte-rrtmgp
reduce_broadband Function
47 statements
Source File
private function reduce_broadband(this, gpt_flux_up, gpt_flux_dn, spectral_disc, top_at_1, gpt_flux_dn_dir) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_fluxes_broadband), intent(inout) :: this
real(kind=wp), intent(in), dimension(:,:,:) :: gpt_flux_up
real(kind=wp), intent(in), dimension(:,:,:) :: gpt_flux_dn
class(ty_optical_props), intent(in) :: spectral_disc
logical, intent(in) :: top_at_1
real(kind=wp), intent(in), optional dimension(:,:,:) :: gpt_flux_dn_dir
Return Value character(len=128)
Calls
Contents
None
Call graph
reduce_broadband calls sum_broadband, extents_are, net_broadband
extents_are calls extents_are_5d, extents_are_3d, extents_are_1d, extents_are_2d_int, extents_are_6d, extents_are_2d, extents_are_4d
net_broadband calls net_broadband_precalc, net_broadband_full