rte_lw – rte-rrtmgp
rte_lw Function
169 statements
Source File
public function rte_lw(optical_props, top_at_1, sources, sfc_emis, fluxes, inc_flux, n_gauss_angles, use_2stream, lw_Ds, flux_up_Jac) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_optical_props_arry), intent(in) :: optical_props
logical, intent(in) :: top_at_1
type(ty_source_func_lw), intent(in) :: sources
real(kind=wp), intent(in), dimension(:,:) :: sfc_emis
class(ty_fluxes), intent(inout) :: fluxes
real(kind=wp), intent(in), optional dimension(:,:), target :: inc_flux
integer, intent(in), optional :: n_gauss_angles
logical, intent(in), optional :: use_2stream
real(kind=wp), intent(in), optional dimension(:,:) :: lw_Ds
real(kind=wp), intent(inout), optional dimension(:,:), target :: flux_up_Jac
Return Value character(len=128)
Calls
Called by
Contents
None
Call graph
rte_lw calls zero_array, expand_and_transpose, any_vals_outside, lw_solver_2stream, lw_solver_noscat_gaussquad, extents_are, any_vals_less_than, rte_lw
zero_array calls zero_array_4d, zero_array_2d, zero_array_3d, zero_array_1d
any_vals_outside calls any_vals_outside_2d_masked, any_vals_outside_3d, any_vals_outside_2d, any_vals_outside_1d, any_vals_outside_3d_masked, any_vals_outside_1d_masked
lw_solver_2stream calls lw_source_2str, lw_combine_sources, adding, lw_two_stream
extents_are calls extents_are_2d_int, extents_are_1d, extents_are_5d, extents_are_6d, extents_are_2d, extents_are_3d, extents_are_4d
any_vals_less_than calls any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_2d, any_vals_less_than_1d, any_vals_less_than_3d, any_vals_less_than_1d_masked
compute_bc calls rte_lw