rte_lw – rte-rrtmgp
rte_lw Function
71 statements
Source File
public function rte_lw(k_dist, gas_concs, p_lay, t_lay, p_lev, t_sfc, sfc_emis, cloud_props, allsky_fluxes, clrsky_fluxes, aer_props, col_dry, t_lev, inc_flux, n_gauss_angles) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_optics), intent(in) :: k_dist
type(ty_gas_concs), intent(in) :: gas_concs
real(kind=wp), intent(in), dimension(:,:) :: p_lay
real(kind=wp), intent(in), dimension(:,:) :: t_lay
real(kind=wp), intent(in), dimension(:,:) :: p_lev
real(kind=wp), intent(in), dimension(:) :: t_sfc
real(kind=wp), intent(in), dimension(:,:) :: sfc_emis
class(ty_optical_props_arry), intent(in) :: cloud_props
class(ty_fluxes), intent(inout) :: allsky_fluxes
class(ty_fluxes), intent(inout) :: clrsky_fluxes
class(ty_optical_props_arry), intent(in), optional :: aer_props
real(kind=wp), intent(in), optional dimension(:,:) :: col_dry
real(kind=wp), intent(in), optional dimension(:,:), target :: t_lev
real(kind=wp), intent(in), optional dimension(:,:), target :: inc_flux
integer, intent(in), optional :: n_gauss_angles
Return Value character(len=128)
Calls
Contents
None
Call graph
rte_lw calls rte_lw, zero_array, expand_and_transpose, any_vals_outside, lw_solver_2stream, lw_solver_noscat_gaussquad, extents_are, any_vals_less_than
zero_array calls zero_array_4d, zero_array_2d, zero_array_3d, zero_array_1d
any_vals_outside calls any_vals_outside_2d_masked, any_vals_outside_3d, any_vals_outside_2d, any_vals_outside_1d, any_vals_outside_3d_masked, any_vals_outside_1d_masked
lw_solver_2stream calls lw_source_2str, lw_combine_sources, adding, lw_two_stream
extents_are calls extents_are_2d_int, extents_are_1d, extents_are_5d, extents_are_6d, extents_are_2d, extents_are_3d, extents_are_4d
any_vals_less_than calls any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_2d, any_vals_less_than_1d, any_vals_less_than_3d, any_vals_less_than_1d_masked