rte_sw – rte-rrtmgp
rte_sw Function
63 statements
Source File
public function rte_sw(k_dist, gas_concs, p_lay, t_lay, p_lev, mu0, sfc_alb_dir, sfc_alb_dif, cloud_props, allsky_fluxes, clrsky_fluxes, aer_props, col_dry, inc_flux) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_optics), intent(in) :: k_dist
type(ty_gas_concs), intent(in) :: gas_concs
real(kind=wp), intent(in), dimension(:,:) :: p_lay
real(kind=wp), intent(in), dimension(:,:) :: t_lay
real(kind=wp), intent(in), dimension(:,:) :: p_lev
real(kind=wp), intent(in), dimension(:) :: mu0
real(kind=wp), intent(in), dimension(:,:) :: sfc_alb_dir
real(kind=wp), intent(in), dimension(:,:) :: sfc_alb_dif
class(ty_optical_props_arry), intent(in) :: cloud_props
class(ty_fluxes), intent(inout) :: allsky_fluxes
class(ty_fluxes), intent(inout) :: clrsky_fluxes
class(ty_optical_props_arry), intent(in), optional target :: aer_props
real(kind=wp), intent(in), optional dimension(:,:) :: col_dry
real(kind=wp), intent(in), optional dimension(:,:) :: inc_flux
Return Value character(len=128)
Calls
Contents
None
Call graph
rte_sw calls rte_sw, sw_solver_noscat, zero_array, any_vals_outside, extents_are, expand_and_transpose, sw_solver_2stream, any_vals_less_than
zero_array calls zero_array_4d, zero_array_2d, zero_array_3d, zero_array_1d
any_vals_outside calls any_vals_outside_2d_masked, any_vals_outside_3d, any_vals_outside_2d, any_vals_outside_1d, any_vals_outside_3d_masked, any_vals_outside_1d_masked
extents_are calls extents_are_2d_int, extents_are_1d, extents_are_5d, extents_are_6d, extents_are_2d, extents_are_3d, extents_are_4d
sw_solver_2stream calls zero_array, sw_dif_and_source, adding
any_vals_less_than calls any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_2d, any_vals_less_than_1d, any_vals_less_than_3d, any_vals_less_than_1d_masked