set_vmr_2d – rte-rrtmgp
set_vmr_2d Function
39 statements
Source File
public function set_vmr_2d(this, gas, w) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_concs), intent(inout) :: this
character(len=*), intent(in) :: gas
real(kind=wp), intent(in), dimension(:,:) :: w
Return Value character(len=128)
Calls
Contents
None
Call graph
set_vmr_2d calls any_vals_outside
any_vals_outside calls any_vals_outside_2d, any_vals_outside_3d, any_vals_outside_1d, any_vals_outside_1d_masked, any_vals_outside_3d_masked, any_vals_outside_2d_masked