source – rte-rrtmgp
source Function
38 statements
Source File
private function source(this, ncol, nlay, nbnd, ngpt, play, plev, tlay, tsfc, jtemp, jpress, jeta, tropo, fmajor, sources, tlev) result(error_msg)
Arguments
Type Intent Optional Attributes Name
class(ty_gas_optics_rrtmgp), intent(in) :: this
integer, intent(in) :: ncol
integer, intent(in) :: nlay
integer, intent(in) :: nbnd
integer, intent(in) :: ngpt
real(kind=wp), intent(in), dimension(ncol,nlay) :: play
real(kind=wp), intent(in), dimension(ncol,nlay+1) :: plev
real(kind=wp), intent(in), dimension(ncol,nlay) :: tlay
real(kind=wp), intent(in), dimension(ncol) :: tsfc
integer, intent(in), dimension(ncol,nlay) :: jtemp
integer, intent(in), dimension(ncol,nlay) :: jpress
integer, intent(in), dimension(2, ncol,nlay,get_nflav(this)) :: jeta
logical(kind=wl), intent(in), dimension(ncol,nlay) :: tropo
real(kind=wp), intent(in), dimension(2,2,2,ncol,nlay,get_nflav(this)) :: fmajor
class(ty_source_func_lw), intent(inout) :: sources
real(kind=wp), intent(in), optional dimension(ncol,nlay+1), target :: tlev
Return Value character(len=128)
Calls
Called by
Contents
None
Call graph
source calls get_nflav, compute_planck_source
gas_optics_int calls source