string_loc_in_array – rte-rrtmgp
string_loc_in_array Function
15 statements
Source File
public pure function string_loc_in_array(string, array)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
character(len=*), intent(in), dimension(:) :: array
Return Value integer
Calls
Called by
Contents
None
Call graph
string_loc_in_array calls lower_case
create_idx_minor_scaling calls string_loc_in_array
reduce_minor_arrays calls string_loc_in_array
compute_gas_taus calls string_loc_in_array
create_idx_minor calls string_loc_in_array
create_key_species_reduce calls string_loc_in_array
init_abs_coeffs calls string_loc_in_array, create_idx_minor_scaling, reduce_minor_arrays, create_idx_minor, create_key_species_reduce
load_int calls init_abs_coeffs
gas_optics_ext calls compute_gas_taus
gas_optics_int calls compute_gas_taus
load_ext calls init_abs_coeffs