validate_2stream – rte-rrtmgp
validate_2stream Function
22 statements
Source File
public function validate_2stream(this) result(err_message)
Arguments
Type Intent Optional Attributes Name
class(ty_optical_props_2str), intent(in) :: this
Return Value character(len=128)
Calls
Contents
None
Call graph
validate_2stream calls extents_are, any_vals_less_than, any_vals_outside
extents_are calls extents_are_2d_int, extents_are_1d, extents_are_5d, extents_are_6d, extents_are_2d, extents_are_3d, extents_are_4d
any_vals_less_than calls any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_2d, any_vals_less_than_1d, any_vals_less_than_3d, any_vals_less_than_1d_masked
any_vals_outside calls any_vals_outside_2d_masked, any_vals_outside_3d, any_vals_outside_2d, any_vals_outside_1d, any_vals_outside_3d_masked, any_vals_outside_1d_masked