zero_array_4D – rte-rrtmgp
zero_array_4D Subroutine
14 statements
Source File
private subroutine zero_array_4D(ni, nj, nk, nl, array) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ni
integer, intent(in) :: nj
integer, intent(in) :: nk
integer, intent(in) :: nl
real(kind=wp), intent(out), dimension(ni, nj, nk, nl) :: array
Called by
Contents
None
Call graph
zero_array calls zero_array_4d
lw_solver_noscat calls zero_array
rte_lw calls zero_array, rte_lw
compute_gas_taus calls zero_array, combine_abs_and_rayleigh
rte_sw calls zero_array, sw_solver_2stream, rte_sw
sw_solver_2stream calls zero_array
combine_abs_and_rayleigh calls zero_array
lw_solver_noscat_gaussquad calls lw_solver_noscat
gas_optics_ext calls compute_gas_taus
gas_optics_int calls compute_gas_taus
compute_bc calls rte_lw, rte_sw