any_vals_less_than – rte-rrtmgp
any_vals_less_than Interface
4 statements
Source File
public interface any_vals_less_than
Calls
Called by
Contents
Module Procedures
any_vals_less_than_1D any_vals_less_than_2D any_vals_less_than_3D any_vals_less_than_1D_masked any_vals_less_than_2D_masked any_vals_less_than_3D_masked
Module Procedures
private function any_vals_less_than_1D(array, check_value)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: array
real(kind=wp), intent(in) :: check_value
Return Value logical
private function any_vals_less_than_2D(array, check_value)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: array
real(kind=wp), intent(in) :: check_value
Return Value logical
private function any_vals_less_than_3D(array, check_value)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: array
real(kind=wp), intent(in) :: check_value
Return Value logical
private function any_vals_less_than_1D_masked(array, mask, check_value)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: array
logical(kind=wl), intent(in), dimension(:) :: mask
real(kind=wp), intent(in) :: check_value
Return Value logical
private function any_vals_less_than_2D_masked(array, mask, check_value)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: array
logical(kind=wl), intent(in), dimension(:,:) :: mask
real(kind=wp), intent(in) :: check_value
Return Value logical
private function any_vals_less_than_3D_masked(array, mask, check_value)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: array
logical(kind=wl), intent(in), dimension(:,:,:) :: mask
real(kind=wp), intent(in) :: check_value
Return Value logical
Call graph
any_vals_less_than calls any_vals_less_than_3d_masked, any_vals_less_than_2d_masked, any_vals_less_than_1d, any_vals_less_than_2d, any_vals_less_than_3d, any_vals_less_than_1d_masked
rte_lw calls any_vals_less_than, rte_lw
validate_1scalar calls any_vals_less_than
compute_gas_taus calls any_vals_less_than
validate_nstream calls any_vals_less_than
rte_sw calls any_vals_less_than, rte_sw
init_base calls any_vals_less_than
cloud_optics calls any_vals_less_than
validate_2stream calls any_vals_less_than
gas_optics_ext calls compute_gas_taus
gas_optics_int calls compute_gas_taus
compute_bc calls rte_lw, rte_sw