any_vals_outside – rte-rrtmgp
any_vals_outside Interface
4 statements
Source File
public interface any_vals_outside
Calls
Called by
Contents
Module Procedures
any_vals_outside_1D any_vals_outside_2D any_vals_outside_3D any_vals_outside_1D_masked any_vals_outside_2D_masked any_vals_outside_3D_masked
Module Procedures
private function any_vals_outside_1D(array, checkMin, checkMax)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: array
real(kind=wp), intent(in) :: checkMin
real(kind=wp), intent(in) :: checkMax
Return Value logical
private function any_vals_outside_2D(array, checkMin, checkMax)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: array
real(kind=wp), intent(in) :: checkMin
real(kind=wp), intent(in) :: checkMax
Return Value logical
private function any_vals_outside_3D(array, checkMin, checkMax)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: array
real(kind=wp), intent(in) :: checkMin
real(kind=wp), intent(in) :: checkMax
Return Value logical
private function any_vals_outside_1D_masked(array, mask, checkMin, checkMax)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: array
logical(kind=wl), intent(in), dimension(:) :: mask
real(kind=wp), intent(in) :: checkMin
real(kind=wp), intent(in) :: checkMax
Return Value logical
private function any_vals_outside_2D_masked(array, mask, checkMin, checkMax)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: array
logical(kind=wl), intent(in), dimension(:,:) :: mask
real(kind=wp), intent(in) :: checkMin
real(kind=wp), intent(in) :: checkMax
Return Value logical
private function any_vals_outside_3D_masked(array, mask, checkMin, checkMax)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: array
logical(kind=wl), intent(in), dimension(:,:,:) :: mask
real(kind=wp), intent(in) :: checkMin
real(kind=wp), intent(in) :: checkMax
Return Value logical
Call graph
any_vals_outside calls any_vals_outside_2d, any_vals_outside_3d, any_vals_outside_1d, any_vals_outside_1d_masked, any_vals_outside_3d_masked, any_vals_outside_2d_masked
rte_lw calls any_vals_outside, rte_lw
compute_gas_taus calls any_vals_outside
delta_scale_2str calls any_vals_outside
validate_nstream calls any_vals_outside
rte_sw calls any_vals_outside, rte_sw
gas_optics_int calls any_vals_outside, compute_gas_taus
set_vmr_2d calls any_vals_outside
set_vmr_1d calls any_vals_outside
cloud_optics calls any_vals_outside
validate_2stream calls any_vals_outside
gas_optics_ext calls compute_gas_taus
compute_bc calls rte_lw, rte_sw