extents_are – rte-rrtmgp
extents_are Interface
5 statements
Source File
public interface extents_are
Calls
Called by
Contents
Module Procedures
extents_are_1D extents_are_2D extents_are_3D extents_are_4D extents_are_5D extents_are_6D extents_are_2d_int
Module Procedures
private function extents_are_1d(array, n1)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: array
integer, intent(in) :: n1
Return Value logical(kind=wl)
private function extents_are_2d(array, n1, n2)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: array
integer, intent(in) :: n1
integer, intent(in) :: n2
Return Value logical(kind=wl)
private function extents_are_3d(array, n1, n2, n3)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: array
integer, intent(in) :: n1
integer, intent(in) :: n2
integer, intent(in) :: n3
Return Value logical(kind=wl)
private function extents_are_4d(array, n1, n2, n3, n4)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:,:) :: array
integer, intent(in) :: n1
integer, intent(in) :: n2
integer, intent(in) :: n3
integer, intent(in) :: n4
Return Value logical(kind=wl)
private function extents_are_5d(array, n1, n2, n3, n4, n5)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:,:,:) :: array
integer, intent(in) :: n1
integer, intent(in) :: n2
integer, intent(in) :: n3
integer, intent(in) :: n4
integer, intent(in) :: n5
Return Value logical(kind=wl)
private function extents_are_6d(array, n1, n2, n3, n4, n5, n6)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:,:,:,:) :: array
integer, intent(in) :: n1
integer, intent(in) :: n2
integer, intent(in) :: n3
integer, intent(in) :: n4
integer, intent(in) :: n5
integer, intent(in) :: n6
Return Value logical(kind=wl)
private function extents_are_2d_int(array, n1, n2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:,:) :: array
integer, intent(in) :: n1
integer, intent(in) :: n2
Return Value logical(kind=wl)
Call graph
extents_are calls extents_are_5d, extents_are_3d, extents_are_1d, extents_are_2d_int, extents_are_6d, extents_are_2d, extents_are_4d
rte_lw calls extents_are, rte_lw
load_lut calls extents_are
compute_gas_taus calls extents_are
delta_scale_2str calls extents_are
reduce_broadband calls extents_are
validate_nstream calls extents_are
rte_sw calls extents_are, rte_sw
init_base calls extents_are
gas_optics_ext calls extents_are, compute_gas_taus
gas_optics_int calls extents_are, compute_gas_taus
reduce_byband calls extents_are
compute_heating_rate calls extents_are
reduce_bygpoint calls extents_are
load_pade calls extents_are
compute_optimal_angles calls extents_are
compute_bc calls extents_are, rte_lw, rte_sw
validate_2stream calls extents_are