net_broadband – rte-rrtmgp
net_broadband Interface
3 statements
Source File
public interface net_broadband
Calls
Called by
Contents
Module Procedures
net_broadband_full net_broadband_precalc
Module Procedures
private subroutine net_broadband_full(ncol, nlev, ngpt, spectral_flux_dn, spectral_flux_up, broadband_flux_net) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncol
integer, intent(in) :: nlev
integer, intent(in) :: ngpt
real(kind=wp), intent(in), dimension(ncol, nlev, ngpt) :: spectral_flux_dn
real(kind=wp), intent(in), dimension(ncol, nlev, ngpt) :: spectral_flux_up
real(kind=wp), intent(out), dimension(ncol, nlev) :: broadband_flux_net
private subroutine net_broadband_precalc(ncol, nlev, flux_dn, flux_up, broadband_flux_net) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncol
integer, intent(in) :: nlev
real(kind=wp), intent(in), dimension(ncol, nlev) :: flux_dn
real(kind=wp), intent(in), dimension(ncol, nlev) :: flux_up
real(kind=wp), intent(out), dimension(ncol, nlev) :: broadband_flux_net
Call graph
net_broadband calls net_broadband_precalc, net_broadband_full
reduce_broadband calls net_broadband