zero_array – rte-rrtmgp
zero_array Interface
3 statements
Source File
public interface zero_array
Called by
Contents
Module Procedures
zero_array_1D zero_array_2D zero_array_3D zero_array_4D
Module Procedures
private subroutine zero_array_1D(ni, array) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ni
real(kind=wp), intent(out), dimension(ni) :: array
private subroutine zero_array_2D(ni, nj, array) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ni
integer, intent(in) :: nj
real(kind=wp), intent(out), dimension(ni, nj) :: array
private subroutine zero_array_3D(ni, nj, nk, array) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ni
integer, intent(in) :: nj
integer, intent(in) :: nk
real(kind=wp), intent(out), dimension(ni, nj, nk) :: array
private subroutine zero_array_4D(ni, nj, nk, nl, array) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ni
integer, intent(in) :: nj
integer, intent(in) :: nk
integer, intent(in) :: nl
real(kind=wp), intent(out), dimension(ni, nj, nk, nl) :: array
Call graph
rte_lw calls zero_array, rte_lw
sw_solver_2stream calls zero_array
rte_sw calls zero_array, rte_sw
lw_solver_noscat calls zero_array
compute_bc calls rte_lw, rte_sw
lw_solver_noscat_gaussquad calls lw_solver_noscat